### ISSUE TITLE
[bug] Error when Updating mods

### ISSUE THREAD

**Issue by TailsFan01** [CreatorsTF/community-launcher#74]
### Prerequisites

- [X] This is not a feature request.
- [X] I checked recent issues and verified that this is not a duplicate.

### UI or mechanical bug?

Mechanical

### Describe the bug

When attempting to update Creators.tf with the launcher, a Mod Install Error pops up, and the mod is not updated. Mod version at the top also reads as 'undefined'. Other updates (such as those for Ultimate TF2 Visual Fix Pack) work completely fine and update without errors. Mod version also appears as normal for other mods.

### Was there an error dialogue for this bug? If so, please, provide its content here. (optional)

SyntaxError: Unexpected End of JSON Input

### Steps to reproduce the behavior

1. Use an older version of the installer (last updated for Manned Machines)
2. Attempt to update 'Creators.TF'
3. Click 'Yes' on the prompt to update, then wait

### Expected behavior

Mod updates, then runs normally if prompted

### Actual behavior

Mod refuses to update.

### Screenshots (optional)

![syntaxerror](https://user-images.githubusercontent.com/52511992/145694966-3779d421-4b67-4619-b96f-77ecc4739a03.PNG)

### Operating system and version

Windows 10 | Launcher version 0.3.0

**Comment by yolojacob5000** [comment]
For anyone else having the same problem, clicking the 'delete' icon in the top right corner, then reinstalling Creators.tf fixes the issue.
